clean:
	rm *.exe

1: 1.cpp
	g++ 1.cpp -o 
	.\1.exe

2: 2.cpp
	g++ 2.cpp -o 
	.\2.exe

3: 3.cpp
	g++ 3.cpp -o 
	.\3.exe

4: 4.cpp
	g++ 4.cpp -o 
	.\4.exe

5: 5.cpp
	g++ 5.cpp -o 
	.\5.exe

6: 6.cpp
	g++ 6.cpp -o 
	.\6.exe

7: 7.cpp
	g++ 7.cpp -o 
	.\7.exe

8: 8.cpp
	g++ 8.cpp -o 
	.\8.exe

9: 9.cpp
	g++ 9.cpp -o 
	.\9.exe

10: 10.cpp
	g++ 10.cpp -o 
	.\10.exe